# Generated by Django 3.2.4 on 2023-07-06 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wowtbc', '0020_auto_20230706_1337'),
        ('payment', '0002_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoinbaseOrder',
        ),
        migrations.AddField(
            model_name='order',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wowtbc.game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('coinbase', 'Coinbase')], default='stripe', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('inprogress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='inprogress', max_length=20),
        ),
    ]
