# Generated by Django 3.2 on 2021-09-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinbaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_id', models.CharField(max_length=255, unique=True, verbose_name='Unique Payment ID')),
                ('coin_type', models.CharField(choices=[('OSRS', 'OSRS'), ('RS3', 'RS3')], default='OSRS', max_length=255, verbose_name='Type')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('email', models.EmailField(blank=True, default='unknown@gmail.com', max_length=254, null=True)),
                ('rsn', models.CharField(blank=True, default='unknown', max_length=50, null=True, verbose_name='RSN')),
                ('order_id', models.CharField(max_length=50, unique=True, verbose_name='Order ID')),
                ('status', models.CharField(choices=[('0', 'New'), ('1', 'Pending'), ('2', 'Confirmed'), ('3', 'Failed'), ('4', 'Delayed'), ('5', 'Resolved')], default='0', max_length=255, verbose_name='Status')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Charge Code')),
                ('used', models.BooleanField(default=False, verbose_name='Coins Delivered')),
            ],
            options={
                'verbose_name_plural': 'Coinbase Orders',
            },
        ),
        migrations.CreateModel(
            name='OSRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osrs_numbers', models.PositiveIntegerField(verbose_name='OSRS')),
                ('rsn', models.CharField(max_length=255)),
                ('email', models.EmailField(default='', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'OSRS',
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('q_type', models.CharField(choices=[('F2P', 'F2P'), ('P2P', 'P2P')], max_length=255, verbose_name='Quest Type')),
                ('regular_price', models.FloatField(verbose_name='Regular Price')),
                ('regular_amount', models.FloatField(verbose_name='Regular Amount')),
                ('ironman_price', models.FloatField(verbose_name='Ironman Price')),
                ('ironman_amount', models.FloatField(verbose_name='Ironman Amount')),
                ('hardcore_price', models.FloatField(verbose_name='Hardcore Ironman Price')),
                ('hardcore_amount', models.FloatField(verbose_name='Hardcore Ironman Amount')),
                ('ultimate_price', models.FloatField(verbose_name='Ultimate Ironman Price')),
                ('ultimate_amount', models.FloatField(verbose_name='Ultimate Ironman Amount')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50, verbose_name='Country')),
                ('feedback', models.TextField(verbose_name='Your Feedback')),
            ],
        ),
        migrations.CreateModel(
            name='RS3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rs3_numbers', models.PositiveIntegerField(verbose_name='RS3')),
                ('rsn', models.CharField(max_length=255)),
                ('email', models.EmailField(default='', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'RS3',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(default='400a848b-d1bd-4c2e-a450-d1032d4c905d', max_length=255, verbose_name='API KEY')),
                ('secret_key', models.CharField(default='25b26b1e-bc0d-4c31-b578-049a6b1c24b0', max_length=255, verbose_name='Secret Key')),
                ('osrs_price', models.FloatField(default=0, verbose_name='OSRS Price (USD)')),
                ('rs3_price', models.FloatField(default=0, verbose_name='RS3 Price (USD)')),
                ('osrs_stock', models.FloatField(default=0, verbose_name='Current OSRS Stock')),
                ('rs3_stock', models.FloatField(default=0, verbose_name='Current RS3 Stock')),
                ('osrs_fee', models.FloatField(default=0, verbose_name='OSRS Fee')),
                ('rs3_fee', models.FloatField(default=0, verbose_name='RS3 Fee')),
                ('osrs_factor', models.FloatField(default=1, verbose_name='OSRS to RS3')),
                ('rs3_factor', models.FloatField(default=1, verbose_name='RS3 to OSRS')),
            ],
        ),
    ]
