# Generated by Django 3.2 on 2023-05-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_review_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_id', models.CharField(max_length=255, unique=True, verbose_name='Unique Payment ID')),
                ('coin_type', models.CharField(choices=[('OSRS', 'OSRS'), ('RS3', 'RS3')], default='OSRS', max_length=255, verbose_name='Type')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('email', models.EmailField(blank=True, default='unknown@gmail.com', max_length=254, null=True)),
                ('rsn', models.CharField(blank=True, default='unknown', max_length=50, null=True, verbose_name='RSN')),
                ('order_id', models.CharField(max_length=50, unique=True, verbose_name='Order ID')),
                ('status', models.CharField(choices=[('0', 'New'), ('1', 'Pending'), ('2', 'Confirmed'), ('3', 'Failed'), ('4', 'Delayed'), ('5', 'Resolved')], default='0', max_length=255, verbose_name='Status')),
                ('used', models.BooleanField(default=False, verbose_name='Coins Delivered')),
            ],
            options={
                'verbose_name_plural': 'Stripe Orders',
            },
        ),
    ]
