# Generated by Django 3.2 on 2023-05-31 04:21

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_stripeorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinbaseorder',
            name='up_id',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=7, unique=True, verbose_name='Unique Payment ID'),
        ),
        migrations.AlterField(
            model_name='stripeorder',
            name='up_id',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=7, unique=True, verbose_name='Unique Payment ID'),
        ),
    ]
