# Generated by Django 3.2 on 2023-05-31 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wowtbc', '0007_alter_game_price'),
        ('main', '0005_auto_20230531_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeorder',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stripe_orders', to='wowtbc.game'),
        ),
    ]
