# Generated by Django 3.2 on 2023-06-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_stripeorder_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinbaseorder',
            name='rsn',
        ),
        migrations.RemoveField(
            model_name='stripeorder',
            name='rsn',
        ),
        migrations.AddField(
            model_name='coinbaseorder',
            name='ign',
            field=models.CharField(blank=True, default='unknown', max_length=50, null=True, verbose_name='IGN'),
        ),
        migrations.AddField(
            model_name='stripeorder',
            name='ign',
            field=models.CharField(blank=True, default='unknown', max_length=50, null=True, verbose_name='IGN'),
        ),
    ]
