# Generated by Django 3.2 on 2023-06-04 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20230604_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='osrs',
            old_name='rsn',
            new_name='ign',
        ),
        migrations.RenameField(
            model_name='rs3',
            old_name='rsn',
            new_name='ign',
        ),
    ]
