# Generated by Django 3.2 on 2023-06-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20230604_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeorder',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='Quantity'),
        ),
    ]
