# Generated by Django 3.2 on 2023-06-04 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_stripeorder_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripeorder',
            name='coin_type',
        ),
    ]
