# Generated by Django 3.2 on 2023-06-04 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_stripeorder_coin_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinbaseorder',
            name='coin_type',
        ),
    ]
