# Generated by Django 3.2.4 on 2023-06-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20230610_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinbaseorder',
            name='order_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Order ID'),
        ),
        migrations.AlterField(
            model_name='stripeorder',
            name='order_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Order ID'),
        ),
    ]
