# Generated by Django 3.2.4 on 2023-06-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20230611_1735'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OSRS',
        ),
        migrations.DeleteModel(
            name='Quest',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='RS3',
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
