# Generated by Django 3.2.4 on 2023-07-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20230711_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(max_length=200, upload_to='shop'),
        ),
        migrations.AlterField(
            model_name='account',
            name='price',
            field=models.FloatField(help_text='Price in USD'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(max_length=200, upload_to='shop'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(help_text='Price in USD'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(max_length=200, upload_to='shop'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.FloatField(help_text='Price in USD'),
        ),
    ]
