# Generated by Django 3.2 on 2022-11-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowtbc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='countries')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='games')),
                ('show_rg', models.BooleanField(default=False, verbose_name='Show Region & Server')),
                ('show_faction', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GameServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SaleMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='sale_methods')),
            ],
        ),
        migrations.AddField(
            model_name='faction',
            name='image',
            field=models.ImageField(null=True, upload_to='factions'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='image',
            field=models.ImageField(null=True, upload_to='PaymentMethod'),
        ),
    ]
