# Generated by Django 3.2 on 2022-11-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowtbc', '0002_auto_20221119_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_method',
            field=models.CharField(max_length=100),
        ),
    ]
