# Generated by Django 3.2 on 2022-11-19 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wowtbc', '0003_alter_paymentmethod_payment_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
    ]
