# Generated by Django 3.2 on 2023-05-30 12:21

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wowtbc', '0004_alter_country_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['title']),
        ),
    ]
