# Generated by Django 3.2 on 2023-06-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowtbc', '0007_alter_game_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gold_type',
            field=models.CharField(default='ABC', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='unit',
            field=models.CharField(choices=[('K', 'K'), ('M', 'M')], default='K', max_length=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.FloatField(help_text='Price per 1 Unit coins'),
        ),
    ]
