# Generated by Django 3.2 on 2023-06-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowtbc', '0008_auto_20230604_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='header_image',
            field=models.ImageField(null=True, upload_to='games', verbose_name='Header Image'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(upload_to='games', verbose_name='Thumbnail'),
        ),
    ]
