# Generated by Django 3.2 on 2023-06-04 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wowtbc', '0009_auto_20230604_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinTypeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='CoinType')),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='header_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wowtbc.cointypeimage'),
        ),
    ]
