# Generated by Django 3.2 on 2023-06-04 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wowtbc', '0010_auto_20230604_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cointypeimage',
            options={'verbose_name': 'Coin Type Image', 'verbose_name_plural': 'Coin Type Images'},
        ),
    ]
