# Generated by Django 3.2.4 on 2023-06-10 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wowtbc', '0012_auto_20230607_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServersList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('servers_list', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='servers_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wowtbc.serverslist'),
        ),
    ]
