# Generated by Django 3.2.4 on 2023-06-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowtbc', '0013_auto_20230610_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverslist',
            name='servers_list',
            field=models.TextField(blank=True, help_text='Comma separated list of servers', null=True),
        ),
    ]
