# Generated by Django 3.2.4 on 2023-06-12 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wowtbc', '0014_alter_serverslist_servers_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-id']},
        ),
    ]
