# Generated by Django 3.2.4 on 2023-06-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowtbc', '0015_alter_game_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
