# Generated by Django 3.2.4 on 2023-06-20 14:16

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wowtbc', '0017_game_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
