# Generated by Django 3.2.4 on 2023-06-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wowtbc', '0018_game_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faction',
        ),
        migrations.DeleteModel(
            name='GameServer',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
