# Generated by Django 3.2.4 on 2023-07-06 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wowtbc', '0019_auto_20230620_1418'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='SaleMethod',
        ),
    ]
